title: Orc's WIKI
email: hwang.jongtaek@gmail.com
description: >- 
  황오크의 개인 위키
baseurl: "/"
url: "https://orchwang.github.io"
twitter_username: orchwang
github_username:  orchwang

plugins:
  - jekyll-feed

sass:
    style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
