# Site settings
title: Orc Hwang's Wiki
description: >-
  개발 학습 기록과 기술 지식을 체계적으로 관리하는 개인 위키입니다.
baseurl: ""
url: "https://orchwang.github.io"
author: Orc Hwang
email: your-email@example.com

# Career settings
career_start_date: 2015-04-01

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
permalink: /:year/:month/:day/:title.html
timezone: Asia/Seoul

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable custom plugins from _plugins directory
plugins_dir: _plugins

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - specs/
  - CLAUDE.md
  - Makefile

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  - scope:
      path: "pages"
    values:
      layout: "default"

# Tag settings
tag_page_layout: tag_page
tag_page_dir: tags

# Category settings
category_page_layout: category_page
category_page_dir: categories
